### ISSUE TITLE
Compilation in VS 2015 (MVC5 project) problems

### ISSUE THREAD

**Issue by rpokrovskij** [ENikS/LINQ#1]
Can't understand how to work with it in Visual Studio without npm. 
Get two types of errors during the compilation:
1) TS2304  "Cannot find name 'Symbol'", and
2) TS2352  Type 'I[]' is not assignable type to type `Iterable<I>`

This was my first attempt to use EcmaScript6 (and shimps) so I'm definitely doing something wrong.

I have downloaded `linq-ts.ts`, `linq-ts.d.ts` from you; `es6-shim.min.js`, `es6-shim.map` from "es6-shim" and `es6-shim.d.ts` from "definetely typed" projects.. But it seems the `es6-shim.d.ts` doesn't contain `Symbol` , when as I see `es6-shim.js` contains it...
Where you get your  `es6-shim.d.ts` with Symbol defined? Or what else d.ts U 

I also need generic advice: may be your project is not suitable to be compiled to EcmaScript5, and you strongly recommend to use only EcmaScript6?

**Comment by ENikS** [comment]
Symbol is not defined in ES5 so es6-shim is used to define missing features. Iterables [] are not implemented in ES5 either...

I would suggest to try following instructions and install it with NPM first. Once you understand the structure of the project and its dependencies just use only what you need and discard the rest.
