### ISSUE TITLE
OfType(...) Method

### ISSUE THREAD

**Issue by ENikS** [ENikS/LINQ#15]
Not sure if this method makes sense in JavaScript

**Comment by pgatilov** [comment]
I would say it does make sense. There is the `instanceof` operator that is similar to c#'s `is`. So yes, we may have collections of some base classes and want to filter out a certain type of descendants.

The only difference is that just a generic `OfType<T>()` won't work even in TypeScript - you have to pass the constructor function inside the method (hello type erasure). But something like this should work:

```
export interface Enumerable<T>
{
  OfType<NewT>(tClass: IClassDecl<NewT>): Enumerable<NewT> {...}
}

export interface IClassDecl<TClass> {
    new (...args: any[]): TClass;
    prototype: any;
}
```
