### ISSUE TITLE
Typescript UpCast compilation issue

### ISSUE THREAD

**Issue by prasanthkarukkuvel** [ENikS/LINQ#2]
In both `TheyBy<T>` and `ThenByDescending<T>` upcast compliation fails

``` typescript
 var superEqual = (<OrderedLinq<T>>this).equal;
```

Since `this` is type of `Linq<T>` typescript (1.7.5) complier throws

>  Type `Linq<T>` is not assignable to type `OrderedLinq<T>`.   Property 'equal' is missing in type `Linq<T>`.

To do a work around assigning `this` to `var self:any = this` is sensible..?

**Comment by ENikS** [comment]
I don't think this is an issue with the library
