### ISSUE TITLE
[Feature Request] Split a list into multiple lists

### ISSUE THREAD

**Issue by bastienJS** [ENikS/LINQ#24]
Hi,

please see this thread: http://stackoverflow.com/questions/419019/split-list-into-sublists-with-linq

Microsoft also have an implementation of the ChunkBy extension method:

https://msdn.microsoft.com/de-de/library/cc138361.aspx

They just forgot... it to put it into the .net framework ;-)

You see any chance that this gets added to your cool library?

See also this table as sample: 15 items per table

![image](https://cloud.githubusercontent.com/assets/5945955/17072838/8454c252-506b-11e6-9314-fb921fad6676.png)

**Comment by ENikS** [comment]
Interesting feature. Let me learn more about it.

**Comment by bastienJS** [comment]
Thanks for the quick job:

```
 var result = Enumerable
           .AsEnumerable(gradings)
           .Select( (g,index) => new GradingKeyPair(g,Math.floor(index/15)))
           .ChunkBy(a => a.index)
           .ToArray();
```

![image](https://cloud.githubusercontent.com/assets/5945955/17079140/5657812c-5107-11e6-84c3-5db80445ce22.png)
