### ISSUE TITLE
Missing interface definition in Typings files.

### ISSUE THREAD

**Issue by hasanayan** [ENikS/LINQ#25]
Hi, first of all thanks for the package. After a few checks on linq packages on npm. This is the only one that worked for me and still being maintained. 
There is a small problem, node.js gives me 

`error TS2304: Cannot find name 'Iterable'.`  upon build. That's because *.d.ts files reference `Iterable<T>` but there is no definition for it.

Adding

```
interface Iterable<T>{

}
```

to both`linq.d.ts` and `enumerable.d.ts` 

and 

```
export interface Map<TKey, TElement>{

}
```

to`enumerable.d.ts` helped me get rid of the errors.

**Comment by ENikS** [comment]
If you are using `linq-es2015` package you must build with "target": "es2015"
Interface Iterable is defined on line 38 of [lib.es2015.iterable.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.iterable.d.ts) and is included in build when target is set to es2015.

If you are building EcmaScript 5.1 compatible project you should use [linq-es5](https://www.npmjs.com/package/linq-es5) node package. It has Iterable and Map defined in included .d.ts file and implementation provided by shim-es6 module.

**Comment by hasanayan** [comment]
Hi @ENikS , Unfortunately switching the package to linq-es5 did not fix this issue for me. 

Here is my tsconfig file:

```
{
    "compilerOptions": {
        "target": "es5",
        "sourceMap": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": true,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true
    }
}
```

The package works perfectly however I still get these errors:

```
****private****/node_modules/linq-es5/lib/enumerable.d.ts(1,40): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(70,104): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(76,23): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(150,22): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(178,91): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(200,31): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(200,132): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(210,25): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(230,26): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(365,58): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(374,26): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(452,95): error TS2304: Cannot find name 'Map'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(461,102): error TS2304: Cannot find name 'Map'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(480,22): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/enumerable.d.ts(507,23): error TS2304: Cannot find name 'Iterable'.
****private****/node_modules/linq-es5/lib/linq.d.ts(14,45): error TS2304: Cannot find name 'Iterable'.
```

**Comment by ENikS** [comment]
Please look at this sample: [Using linq-es2015 in TypeScripts ](https://github.com/ENikS/LINQ/tree/examples/TypeScript).

It builds and runs with latest TypeScript compiler, just copy settings from the project.

**Comment by fayezmm** [comment]
I am facing the same problem with the "[linq-es5](https://www.npmjs.com/package/linq-es5)" not "linq-es2015".  I need the linq-es5 version ... are there any workarounds for this issue.

**Comment by ENikS** [comment]
Update to the latest (v1.11.1 or later). 
Add `***/node_modules/linq-es5/typings/es6-shim.d.ts` to your project

**Comment by WinInsider** [comment]
With TypeScript 2.0+ is possible to use TypeScript's own ECMAScript lib definitions... this is done via libs:["es6"] in tsconfig.json... this eliminates direct references to es6-shim... and works for both ES5 and ES6 TS Targets... 

On another topic, core-js may be more preferred runtime shim

**Comment by ENikS** [comment]
I'll look into it when time permits

**Comment by ENikS** [comment]
I do not see any benefit of switching from one shim to the other. Unless you could show me ANY benefit in doing so I'd rather leave it alone.

**Comment by WinInsider** [comment]
I may have confused my message... 

is line 17 in linq-es5/lib/linq.ts required? >> import "es6-shim"

Don't TypeScripts 2.0 own libs have definition of Enumerable, IEnumerable, IEnumerator... may require to include [libs] in tsconfig.json

**Comment by ENikS** [comment]
LINQ-ES5 targets old version of node and browsers. These do not implement new features of ecmascript.
