### ISSUE TITLE
Functions are exported as "function* ..."

### ISSUE THREAD

**Issue by hasanayan** [ENikS/LINQ#26]
I am consuming the package as follows:
`import {asEnumerable, Range} from "linq-es2015";`

it builds without errors and works on my desktop firefox. However it does not work on iOS or Mac Safari. Because my output js file contains functions like:

```
function* Forward(target) {
        yield* target;
    }
    exports.Forward = Forward;
    function* Reverse(target) {
        for (let i = target.length - 1; i >= 0; i--) {
            yield target[i];
        }
    }
    exports.Reverse = Reverse;
    function* Select(target, transform) {
        let index = 0;
        for (let value of target) {
            yield transform(value, index++);
        }
    }
```

what does function\* mean? And why does linq-es2015 produces it?

**Comment by ENikS** [comment]
Safari is not yet es2015 compatible browser. You need [linq-es5](https://www.npmjs.com/package/linq-es5) package to work in iOS. 
Just include this in your page:

```
<script type="text/javascript" src="//npmcdn.com/linq-es5/dist/linq.min.js"></script>
```

**Comment by hasanayan** [comment]
Thanks @ENikS , That solved the problem for me
