### ISSUE TITLE
How to import linq-es2015?

### ISSUE THREAD

**Issue by richerp** [ENikS/LINQ#28]
in package.json
"dependencies": {
...
"linq-es2015": "2.4.4",
...

in systemjs.config.js
var map = {
...
'linq-es2015': 'node_modules/linq-es2015'
...

var packages = {
...
 'linq-es2015': { main: 'index.js', defaultExtension: 'js' }
...

in gulpfile.js
gulp.src('./node_modules/linq-es2015/*_/_.js').pipe(gulp.dest('./wwwroot/node_modules/linq-es2015'));

then in xxx.ts file:
import \* as Enumerable from "linq-es2015";

ngOnInit() {
var count = Enumerable.asEnumerable([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
            .Where(a => a % 2 == 1)
            .Count();

```
    alert(count);
```

...

but when run in chrome ,
Error: XHR error (404 Not Found) ...
Error loading http://localhost:5000/node_modules/linq-es2015/index.js as "linq-es2015" from http://localhost:5000/app/xxxx.js

can anyone help me?
why error happied?

**Comment by ENikS** [comment]
Why don't you use one of the provided examples?

To be used in chrome linq-es2015 has to be processed by browserify utility. There are sample projects [here](https://github.com/ENikS/LINQ/tree/examples/TypeScript) and [here](https://jsfiddle.net/ENikS/pyvjcfa0/). Home page for the project has all the required info as well.

If you need already processed module look under latest [releases](https://github.com/ENikS/LINQ/releases). You will find regular as well as minified modules attached to the release.

**Comment by richerp** [comment]
Thanks for your response. But the error still happen.

**Comment by ENikS** [comment]
@richerp can you post html (header where you are importing the library) page here or point me to your code on github?

**Comment by richerp** [comment]
Could you tell me your email ? I send these code to you?

**Comment by richerp** [comment]
This vs project has many files.

**Comment by ENikS** [comment]
Create repo here, on GitHub. Put that page there and send me a link...

**Comment by richerp** [comment]
@ENikS 
https://github.com/richerp/WebApp or https://github.com/MMA2017/WithRicherp
unzip WebApp.zip ,open with vs2015, run it . in file App/app.ts .

**Comment by ENikS** [comment]
Please look at [this sample](https://github.com/ENikS/LINQ/tree/examples/Angular) for correct configuration.
In short, you need to add mapping for the module to be correctly referenced by the loader. For list of changes you  need to make look at [this](https://github.com/ENikS/LINQ/commit/abbf0411665fdfd828748636196bff86b304b7ad) commit

**Comment by richerp** [comment]
@ENikS Thank you very much.I lost 'linq-es2015': { main: 'dist/linq.js', defaultExtension: 'js' }.
It is working correctly.
