### ISSUE TITLE
Add greenkeeper bot to this repository to automatically upgrade dependencies

### ISSUE THREAD

**Issue by StefH** [ENikS/LINQ#30]
See https://greenkeeper.io/

**Usage:**
Three simple commands: Open your terminal, and

```
npm install -g greenkeeper
greenkeeper login
```

Your browser will open and ask you to log in to GitHub. Please do that.
Then, inside the repo you want to keep up to date, do

```
greenkeeper enable
```

and you’re done! Your first greenkeeper PR will arrive shortly!

Checkout my fork from this project to see how this works:
https://github.com/StefH/LINQ/pull/1

**Comment by ENikS** [comment]
I do see your point about importance of keeping things up to date but unfortunately greenkeeper requires GitHub login info to be sent and stored on their server. It does not integrate with GitHub OAuth API. I will have to do some digging...

**Comment by ENikS** [comment]
Well, looks like it does support OAuth, my assumption was incorrect. I've enabled the repository so it will be updated automatically. Thank you for the tip!
