### ISSUE TITLE
error TS2304, TS2345, TS2339, TS7006

### ISSUE THREAD

**Issue by QJesus** [ENikS/LINQ#34]
Hi, I'm using linq-es2015@2.4.9 and typescript@1.8.10
I want to use linq-es2015 with typescript, so I follow this [tutorial](https://github.com/ENikS/LINQ/tree/examples/TypeScript)
I copyed the app.ts to compile but failed.

qpan@qpan-vm:~/Desktop/$ tsc
node_modules/linq-es2015/lib/enumerable.d.ts(1,40): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(70,115): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(76,23): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(150,22): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(178,91): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(200,31): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(200,132): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(210,25): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(230,26): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(365,58): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(374,26): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(452,95): error TS2304: Cannot find name 'Map'.
node_modules/linq-es2015/lib/enumerable.d.ts(461,102): error TS2304: Cannot find name 'Map'.
node_modules/linq-es2015/lib/enumerable.d.ts(480,22): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/enumerable.d.ts(507,23): error TS2304: Cannot find name 'Iterable'.
node_modules/linq-es2015/lib/linq.d.ts(6,44): error TS2304: Cannot find name 'Iterable'.
routes/ts/attend/attend.ts(8,50): error TS2345: Argument of type '(longest: string, next: {}) => {}' is not assignable to parameter of type '(aggr: string, x: {}) => string'.
  Type '{}' is not assignable to type 'string'.
routes/ts/attend/attend.ts(8,74): error TS2339: Property 'length' does not exist on type '{}'.
routes/ts/attend/attend.ts(10,39): error TS7006: Parameter 'fruit' implicitly has an 'any' type.

can you help me ?

**Comment by StefH** [comment]
You probably need some typings for es6?

**Comment by ENikS** [comment]
**Verify that you are running node `v6.x.x`** by running `node -v` in a terminal/console window. Older versions produce errors. If you need to run it with older node version substitute [LINQ-ES2015](https://www.npmjs.com/package/linq-es2015) with [LINQ-ES5](https://www.npmjs.com/package/linq-es5) package.

**Comment by QJesus** [comment]
oh haha my bad. thank you very much. 

my tsconfig.json had an error:    "target": "es5";
it should be "target": "es2015"

thank you again.
