### ISSUE TITLE
SequenceEqual bug

### ISSUE THREAD

**Issue by ralphwaldo** [ENikS/LINQ#38]
When two sequences are the same length, there is one more iteration than there should be (compared to C#). It matters when using a custom comparer, unless it checks for undefined. See
[https://jsfiddle.net/ralphwaldo29/xj5aox7k/](url)

**Comment by ENikS** [comment]
Your link is not working, did you forget to share it?

**Comment by ENikS** [comment]
Thank you for the fiddle, it was very easy to get it fixed with it!

**Comment by ralphwaldo** [comment]
You're welcome! Great library, btw - and impressive turnaround on the bug!
