### ISSUE TITLE
Different expectations how the ChunkBy works in special scenario

### ISSUE THREAD

**Issue by bastienJS** [ENikS/LINQ#39]
Before I put a a repo app on plunkr I would like to know wether this is a bug or my excpectations are just wrong.

**Thats the code I run**

```
let pageCount = 11;
let resultLength = result.length;

let gradingKeys = Enumerable.From(result)
.Select((item, index) => {
    return { grade: item.grade, scores: item.scores, index: Math.floor(item.index / pageCount) } 
    // Unexpected behavior: as the result array has a length of 11 the ChunkBy returns an empty array?
}
)
.ChunkBy(g => g.index)
.ToArray();
```

For all 11 objects in the result array I do a Select function where **each** anonym object 'index' property is calculated to **0**.

**My expectation how it should work**

That means when when the ChunkBy on the index property is done I expected a flat list of 11 items.

**How it really worked**

After the ChunkBy is done I got an array of length **0**

**My assumption**

**Incorrect behavior** 
- When the pageCount equals or is larger than the length of the result array then I recieve an empty array

**Correct behavior**
- When the pageCount has a lower size like 10 than the I recieve 2 grouped lists.
  list1 with 10 items, list2 with 1 item.

Would you please be that kind and tell me wether the ChunkBy has bug or I need to fix things on my side. Also I must say I would prefer on your side so everyone else has not to do it, but lets discuss it ;-)

**Comment by ENikS** [comment]
Bastien, you should know the drill by now ;)
Could you provide something I could run and test? Perhaps something on fiddler?

**Comment by ENikS** [comment]
... or you could post content of the array in this case:

```
let pageCount = 11;
let resultLength = result.length;

let gradingKeys = Enumerable.From(result)
.Select((item, index) => {
    return { grade: item.grade, scores: item.scores, index: Math.floor(item.index / pageCount) } 
}
)
.ToArray();
```

Basically content of the sequence without the ChunkBy(...)

**Comment by bastienJS** [comment]
Yes I should but I am lazy  - sometimes ;-) -
The arrays content has 11 items where each item index property has the value '0'. The grade/scores stuff should not interest you I just assume...

**Comment by ENikS** [comment]
Bastien, thank you for the QA! Very good catch.
