### ISSUE TITLE
Update to Typescript 1.8

### ISSUE THREAD

**Issue by MeirionHughes** [ENikS/LINQ#4]
I quite like the look of this project; but it looks like it needs updating. 

For example, with the latest TypeScript you can let the compiler deal with generating the definitions. 

You can also use the "typings" field in `package.json` (point it to the typings definition), that way when people install your module via npm, typescript and IDE's can automatically pick up the typings without fanfare. 

Should also have a dist folder containing the typescript compiled, at least, for system and commonjs module formats (with package.json pointing to the commonjs one. That way you can support node.js apps and browser-based apps (that use module loaders).

**Comment by ENikS** [comment]
Thank you for the suggestions. Will update it when time permits.
... or perhaps you could contribute changes?

**Comment by MeirionHughes** [comment]
yeah, I may do; I need a linq solution and I prefer your approach over others (working on-top of an iterator).

**Comment by et1975** [comment]
+1 for update.
TS noob here, went through the type imports, now can't figure why Array[T] can't be converted to Iterable or Enumerable...

**Comment by ENikS** [comment]
I am working on it. Stay tuned...

**Comment by ENikS** [comment]
- The project is building with TSC 1.8.11
- Added "typings" entry pointing to ling-xxx.d.ts
- Compiled with option to generate UMD modules, should be good for node as well as browser
- I've decided against allowing definition file to be generated by the TSC. The interface is governed by the  C# implementation and should be source code compatible with the original. I think it is nice when you could just cut/paste code from C# (with reasonable formatting changes).

**Comment by ENikS** [comment]
Could you give more context to the problem? Can you tell more about what you doing?
