### ISSUE TITLE
Incorrect definition of Enumerable.Concat

### ISSUE THREAD

**Issue by fsoikin** [ENikS/LINQ#44]
The `Enumerable.Concat` method [is defined](https://github.com/ENikS/LINQ/blob/master/lib/enumerable.ts#L105) like this:

```
Concat<V>(second: Iterable<T>): Enumerable<V>;
```

This makes it impossible or TS to infer the type `V`, because it is not used in parameters, so type `V` always ends up being `{}`.
The correct definition should be this:

```
Concat<V>(second: Iterable<V>): Enumerable<V&T>;
```

**Comment by ENikS** [comment]
Nice catch, thanks for the tip!
