### ISSUE TITLE
Contains() work not right. 

### ISSUE THREAD

**Issue by QJesus** [ENikS/LINQ#51]
``` typescript

import { asEnumerable as linq } from 'linq-es2015';

var b = linq("Volvo Black jejtyj 2005").Contains("Volvo");
console.log(b);  // false

```

**Comment by ENikS** [comment]
You are comparing string "Volvo Black jejtyj 2005" and "Volvo". These are two different strings. Contains works on arrays of strings.
Instead try ["Volvo", "Black", "jejtyj", "2005"] or you could do split("Volvo Black jejtyj 2005") to separate words into array.

**Comment by QJesus** [comment]
THX.
