### ISSUE TITLE
VS 2015: Cannot find module 'linq-ts'

### ISSUE THREAD

**Issue by orif** [ENikS/LINQ#6]
Probably suggestion for typings in #4 not implemented yet (or at least npm repository is not up to date).

**Comment by ENikS** [comment]
Could you give more context to the problem? Can you tell more about what you doing?

**Comment by orif** [comment]
I installed the package via "npm i --save ts-linq".
Then I added the below to my existing .ts file:
`
import { asEnumerable, Range } from "linq-ts";
`

Then I got the error: Cannot find module 'linq-ts'.
I think, VS 2015 would automatically find typings if the package.json of ts-linq contained "typings" property.

**Comment by ENikS** [comment]
I have not published a new package. Still working on few things.

**Comment by ENikS** [comment]
Added "typings" entry to the package.json
Browserified and uglified versions are available as downloads in release 1.8.6

**Comment by ENikS** [comment]
It turns out that Import \* from "" did not like current declaration.
