### ISSUE TITLE
Custom providers or only collections

### ISSUE THREAD

**Issue by jeusdi** [ENikS/LINQ#64]
Does it support the possibility to work with providers? Or it only works on collections? For example, could it be possible to create an odata provider?

**Comment by ENikS** [comment]
As long as it is Iterable it should be supported.
Could you point me to spec for the provider you are talking about?

**Comment by jeusdi** [comment]
I meant, a linq provider for odata...

**Comment by ENikS** [comment]
I have no clue what provider means in this context. Could you be more specific?
I would be happy to add the thing but I need to understand what it is

**Comment by ENikS** [comment]
Still waiting for the provider spec :)

**Comment by jeusdi** [comment]
Sorry, please take a took on [here](http://www.c-sharpcorner.com/blogs/linq-providers1).

Linq is only an query dsl. So there're several providers that translate these queries to odata, collections, sql, excel, and so on... you are able to create your own linq provider using helping-libraries like [re-linq](https://github.com/re-motion/Relinq).

Do you know what I mean?

**Comment by ENikS** [comment]
All these are for C#. 
In Javascript anything that could be iterated over is already supported by the library. Is there something specific you are trying to do?
