### ISSUE TITLE
GroupBy typing incorrect

### ISSUE THREAD

**Issue by MgSam** [ENikS/LINQ#69]
The typing on GroupBy is not correct. It is currently defined as this:
``` TypeScript
GroupBy<K, E, R>(selKey: (x: T) => K, selElement?: (x: T) => E, selResult?: (a: K, b: Iterable<E>) => R): Enumerable<R>;
```

It should return an `IGrouping<K, R>` instead.

**Comment by ENikS** [comment]
Do you want to send a PR?

**Comment by MgSam** [comment]
Done. Let me know if any issues.

**Comment by ENikS** [comment]
Thank you

**Comment by MgSam** [comment]
@ENikS We just realized we actually need the linq-es5 package instead. Do you have to do anything special to publish an updated version of that package with the changes I committed?

**Comment by ENikS** [comment]
Just send me another pull request, I'll deploy it

**Comment by MgSam** [comment]
@ENikS I see there's a bunch of differences in linq.ts between the two branches. Is that intentional or has master just not been merged into linq-es5 in a while?

**Comment by ENikS** [comment]
It is intentional
