### ISSUE TITLE
can't call methods on IGrouping

### ISSUE THREAD

**Issue by jmagaram** [ENikS/LINQ#73]
I installed 2.4.32 in my package.json. This code compiles but fails at runtime. I tried calling Count() on the grouping and that didn't work either. This is from TypeScript, most recent VS Code, recent create-react-app.

    test("create and group 1000 items", () =>
        expect(Linq
            .Range(1, 1000)
            .Select(i => i)
            .GroupBy(i => i)
            .Select(i => i.Where(j => true)) // error i.Where is not a function.
            .Count()).toBe(1000));

**Comment by jmagaram** [comment]
I'm new to GitHub and javascript. Help me out here. The code below works. Grouping produces something that subclasses Array (see below) so 'length' works but '.Count' and other linq operators do not. Not sure why intellisense thinks .Count should work.

    test("linq group", () => {
        let x = Linq.from([1, 2, 2, 3, 4, 5]);
        let result = x
            .Where(i => i != 3)
            .GroupBy(i => i)
            .Select(i => (i as any).length)
            .Max();
        expect(result).toBe(2);
    });

    // you defined it this way
    export interface IGrouping<K, R> extends Array<R> {
        key: K
    }

**Comment by jmagaram** [comment]
Try it here. Does not work.

https://codesandbox.io/s/l97norvo27

**Comment by ENikS** [comment]
Grouping is nothing more than a regular array. In order to use it with all the LINQ methods you have to convert it into Enumerable:
```JavaScript
const maxOfAnyItem = Linq.asEnumerable(numbers)
  .GroupBy(i => i)
  .Select(i => Linq.asEnumerable(i).Count())
  .Max();
```

**Comment by jmagaram** [comment]
That probably works but isn’t intuitive to use. For some reason, VS Code provides TypeScript intellisense on the result of GroupBy and thinks that all the regular LINQ operators exist. No compilation error. Only a runtime error, which is dangerous. It also is completely incompatible with the way it works in C#.

________________________________

**Comment by ENikS** [comment]
Do you have a solution in mind?

**Comment by jmagaram** [comment]
The code could automatically wrap the result of GroupBy in asEnumerable. Or somehow change the type definitions so the user knows they are just getting and Array with a Key property. Mostly I don’t understand why TypeScript thinks GroupBy is returning something that has Count, Max, etc methods available when it doesn’t.

Don’t you agree this is a problem? Otherwise forget GroupBy for a second. How do I know that calling Count or Max on a regular enumerator BEFORE calling GroupBy should work either? TypeScript and Intellisense think all those methods are available - which is the entire purpose and point of your library - and they work as expected. But it all explodes when trying to use the result of GroupBy. Totally unpredictable.

I’m only about 2 weeks into learning JavaScript and TypeScript and I’ve looked at the code and don’t know what is wrong or how to fix it.

________________________________

**Comment by jmagaram** [comment]
Also each individual result of GroupBy should probably be lazily evaluated too, not an array.

________________________________

**Comment by ENikS** [comment]
Would you like to try it out and report on performance overhead? I am afraid it would make it much slower. This whole IGrouping interface is remnant from C# and serves no purpose in JavaScript.

**Comment by jmagaram** [comment]
I’ll certainly download and try out any fix you provide. I am not capable of evaluating performance. If it is all lazy then there should not be any performance issue. I don’t understand though. Grouping serves an important purpose in Javascript and any other language. Suppose you have a list of sales of products and you want to know how many of each product you sold in January - you do that with grouping sales by product and then filtering each group by January and then counting the result.

________________________________
