### ISSUE TITLE
Missing production files version 2.4.35

### ISSUE THREAD

**Issue by clystian** [ENikS/LINQ#88]
We get a new version 2.4.35 but oh surprise! cannot find linq.min.js and linq.js from dist folder

We use this package for backend and frontend but
for web -> [https://unpkg.com/linq-es2015/dist/linq.min.js](https://unpkg.com/linq-es2015/dist/linq.min.js)
We get a `Cannot find "/dist/linq.min.js" in linq-es2015@2.4.35` really is last version 
but [https://unpkg.com/linq-es2015@2.4.34/dist/linq.min.js](https://unpkg.com/linq-es2015@2.4.34/dist/linq.min.js) works fine, files exist :)

### dist folder
![image](https://user-images.githubusercontent.com/1278819/70533686-8eb32100-1b27-11ea-9702-08f4cc302a31.png)

### Production files
![image](https://user-images.githubusercontent.com/1278819/70533795-cb7f1800-1b27-11ea-9578-3f4c9ac4231c.png)

### In new version those files doesn't exist
![image](https://user-images.githubusercontent.com/1278819/70533765-bdc99280-1b27-11ea-809c-8273228f6ffe.png)

we go back to version 2.4.34 meanwhile

can we wait for some solution? or you recommend migrate our code importing from source and no-minified version from folder `/lib`?

**Comment by ENikS** [comment]
Fixed in 2.4.36
