### ISSUE TITLE
Sorting using ThenBy or ThenByDescending in a chain is not immutable as in C#

### ISSUE THREAD

**Issue by barakbbn** [ENikS/LINQ#94]
```ts
const base = items.OrderBy(x => x.name);
const asc  = base.ThenBy(x => x.grade);
const desc = base.ThenByDescending(x => x.age);
```
variable `asc` is affected by variable `desc` since additional ordering on variable `base` is not immutable
and actually `asc`, `desc` and `base` are the same object instance

**Comment by ENikS** [comment]
Published 2.5.1
Thank you for help!
